<div class="">
    <style>
        .svg-loader{
            height:30%;
            width: 30%;
            border-radius:50%;
            
        }
    </style>
    <h4 class="ps-2">Update Table</h4>
    <p class="text-end">@livewire('table-name',['tableName'=>$tableName])</p>
    <form>
        <input type="file" wire:model="file" id="file" class="form-control w-50">
        <small class="text-dark ps-1"> File name must be <b>{{ $tableName }}.csv</b></small>

        @error('file')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </form> 
    <div class="ps-2">
        @if ($message)
            @foreach ($message as $m)
              <p class="text-black"> # {{ $m }}</p>
            @endforeach
        @endif     
    </div>
    @if (!$processing)        
   
    @if ($ignorebtn)
        <button wire:click="ignore" class="btn btn-primary btn-sm ms-5 ">Ignore</button>  
    @endif
    @if ($importBtn)
        <button wire:click="import" class="btn btn-success btn-sm ms-5 ">Import</button>      
    @endif
    @endif
 {{-- Loader --}}
 <br>
 <div wire:loading wire:target="file, ignore, import" class="ms-5">
     <svg class="svg-loader" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="163" height="163" style="shape-rendering: auto; display: block; background: rgb(255, 255, 255);" xmlns:xlink="http://www.w3.org/1999/xlink"><g><path style="transform:scale(0.8);transform-origin:50px 50px" stroke-linecap="round" d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z" stroke-dasharray="42.76482137044271 42.76482137044271" stroke-width="8" stroke="#e90c59" fill="none">
         <animate values="0;256.58892822265625" keyTimes="0;1" dur="1s" repeatCount="indefinite" attributeName="stroke-dashoffset"></animate>
       </path><g></g></g><!-- [ldio] generated by https://loading.io --></svg>
 </div>
    @if ($diff)   
        <h3>Changes in fields: </h3>    
        <table class="table table-bordered table-hover table-striped">
            <tr>
                <th>Key</th>
                <th>Field</th>
                <th>Old Data</th>
                <th>New Data</th>
            </tr>

            @foreach ($diff as $key => $data)
                <tr>
                    <td>{{ $data['row_1'][1] }}</td>
                    <td> {{ $header[$data['difference_column']] }} </td>
                    <td>{{ $data['difference_value']['old_value'] }}</td>
                    <td>{{ $data['difference_value']['new_value'] }}</td>
                </tr>
            @endforeach

        </table>
    @endif

   
</div>
